apiVersion: v1
kind: ReplicationController
metadata: 
  name: dockerhub-hello.example.com
spec:
  replicas: 2
  selector: 
    app: dockerhub-hello
  template:
    metadata:
      labels:
        app: dockerhub-hello
    spec:
      containers:
      - name: dockerhub-hello
        image: marceloserpa/dockerhub-hello:v1.0.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080