apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: dockerhub-hello
        image: marceloserpa/dockerhub-hello:v1.0.0
        imagePullPolicy: "Always"
        ports:
        - name: nodejs-port
          containerPort: 8080