apiVersion: v1
kind: Pod
metadata: 
  name: hello-app.example.com
  labels:
    app: hello-app
spec:
  containers:
  - name: hello-deployment-app
    image: marceloserpa/hello-deployment-app:v0.1.0
    imagePullPolicy: "Always"
    ports:
    - name: nodejs-port
      containerPort: 9000