apiVersion: v1
kind: Endpoints
metadata:
    name: {{ .Values.redisExternalService.name }}
subsets:
  - addresses:
      - ip: {{ .Values.redisExternalService.ipAddress }}
    ports:
      - port: {{ .Values.redisExternalService.port }}
