apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisExternalService.name }}
spec:
  type: {{ .Values.redisExternalService.type }}
  ports:
    - port: {{ .Values.redisExternalService.port }}
      targetPort: {{ .Values.redisExternalService.targetPort }}
      protocol: TCP 