apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app
  namespace: test-1   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      serviceAccountName: test-1-sa
      containers:
      - name: nginx-app
        image: nginx:1.14.2
        ports:
        - containerPort: 80
