apiVersion: v1
kind: Pod
metadata: 
  name: dockerhub-hello.example.com
  labels:
    app: dockerhub-hello
spec:
  containers:
  - name: dockerhub-hello
    image: marceloserpa/dockerhub-hello:v1.0.0
    imagePullPolicy: "Always"
    ports:
    - containerPort: 8080