apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpoc-deployment
  labels:
    app: springboot4-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot4-poc
  template:
    metadata:
      labels:
        app: springboot4-poc
    spec:
      containers:
      - name: springboot4-poc
        image: springboot4-poc:0.0.3
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: springboot4-poc-configmap
        - secretRef:
            name: test-db-secret