apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  reverseproxy.conf: |
    server {
      listen  80;
      server_name localhost;

      location / {
        proxy_bind 127.0.0.1;
        proxy_pass http://127.0.0.1:9000;        
      }

      error_page 500 502 503 504 /50x.html
      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:

      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-conf-v
  
      - name: hello-deployment-app
        image: marceloserpa/hello-deployment-app:v0.1.0
        imagePullPolicy: "Always"
        ports:
        - name: nodejs-port
          containerPort: 9000

      volumes:
      - name: nginx-conf-v
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: reverseproxy.conf
              path: reverseproxy.conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx