apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-database
  name: mongo-service
spec:
  ports:
  - name: mongo-port
    port: 27017
    protocol: TCP
    targetPort: 27017
  clusterIP: "None"
  selector:
    app: mongo-database