apiVersion: v1
kind: Pod
metadata: 
  name: leaderboard-poc.com
  labels:
    app: leaderboard-poc
spec:
  containers:
  - name: leaderboard-poc
    image: marceloserpa/leaderboard-poc:v0.0.2-SNAPSHOT
    imagePullPolicy: "Always"
    ports:
    - name: nodejs-port
      containerPort: 3000
    env:
    - name: REDIS_HOST
      value: redis-service  

---

apiVersion: v1
kind: Service
metadata: 
  name: leaderboard-poc-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: leaderboard-poc
  type: NodePort

--- 

apiVersion: v1
kind: Service
metadata:
    name: redis-service
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: NodePort

---

apiVersion: v1
kind: Endpoints
metadata:
    name: redis-service
subsets:
  - addresses:
      - ip: 192.168.0.10
    ports:
      - port: 6379