kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-adm-binding
  namespace: development
subjects:
- kind: User
  name: development-eng
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-adm
  apiGroup: ""